# Generated by Django 2.2b1 on 2019-03-20 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Songs',
            new_name='gana',
        ),
    ]
