# Generated by Django 2.2b1 on 2019-03-21 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20190320_1255'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='gana',
            new_name='song',
        ),
    ]
